name: 'dbt_results'
version: '1.0.0'
config-version: 2

profile: 'dbt_results'

clean-targets:
  - "target"
  - "dbt_modules"
  - "dbt_packages"
  - "logs"

on-run-end: 
  - "{{ log_dbt_results(results) }}"

models:
  dbt_results:
    +materialized: table
    +database: |        
      {%-   if target.name == "sbx_target" -%} us-atldm-test-dev-9198 
      {%- elif target.name == "dev_target" -%} us-atldm-test-dev-9198
      {%- elif target.name == "acc_target" -%} us-atldm-test-qa-2114
      {%- elif target.name == "prd_target" -%} us-atldm-test-prd-99b5
      {%- else -%} us-atldm-test-dev-9198
      {%- endif -%}
    +schema: dbt_monitoring
    +tags: 
      - monitoring
