#Profiles configuration.
dbt_results:
  target: sbx_target
  outputs:
    sbx_target:
      schema: sbx_not_used # unused - default schema
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      threads: 3
      timeout_seconds: 1200
      type: bigquery
    dev_target:
      dataset: tst_not_used # unused - default schema
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      threads: 3
      timeout_seconds: 1200
      type: bigquery
    acc_target:
      dataset: acc_not_used # unused - default schema
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      threads: 3
      timeout_seconds: 1200
      type: bigquery
    prd_target:
      dataset: prd_not_used # unused - default schema
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      threads: 3
      timeout_seconds: 1200
      type: bigquery
